# Generated by Django 5.0.14 on 2025-12-14 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=225)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.CharField(max_length=225)),
                ('Password', models.CharField(max_length=225)),
            ],
        ),
    ]
