# Generated by Django 5.0.14 on 2025-12-14 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_adminusers_sweets'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sweets',
            old_name='des',
            new_name='Category',
        ),
    ]
