# Generated by Django 5.0.14 on 2025-12-14 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_rename_des_sweets_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminusers',
            name='username',
            field=models.CharField(default='Admin', max_length=225),
        ),
    ]
