# Generated by Django 5.0.14 on 2025-12-14 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_adminusers_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=225)),
                ('sweet', models.CharField(max_length=225)),
                ('quantity', models.CharField(max_length=225)),
                ('address', models.CharField(max_length=225)),
                ('phone', models.CharField(max_length=225)),
            ],
        ),
    ]
