# Generated by Django 5.0.14 on 2025-12-14 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sweets',
            name='Stock',
            field=models.IntegerField(),
        ),
    ]
